#!/bin/bash

start_server() {
  export CI=1
  docker run --rm -p 18080:80 --name httpbin -d kennethreitz/httpbin
  make run &
  while ! test -e /tmp/cache-stnsd.sock > /dev/null 2>&1; do sleep 1; echo 'sleeping'; done;
}

stop_server() {
  PID=$(lsof /tmp/cache-stnsd.sock | tail -1 | awk '{print $2}')
  docker rm -f httpbin
  kill -SIGINT $PID
  if [ $? -ne 0 ]; then
    echo "process not found"
    exit 1
  fi
  sleep 1
  kill -0 $PID 2>/dev/null
  if [ $? -ne 1 ]; then
    echo "sent signal as SIGKILL"
    kill -SIGKILL $PID
  fi
}

case "$1" in
  start)
    start_server
    ;;
  stop*)
    stop_server
    ;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 2
esac
