version: '3'
services:
  cache_almalinux9:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.almalinux-9
      args:
        GO_VERSION: 1.18.2
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: el9
    command: make rpm
  cache_centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
      args:
        GO_VERSION: 1.18.2
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: el7
    command: make rpm
  cache_ubuntu20:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-20
      args:
        GO_VERSION: 1.18.2
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: focal
    command: make deb
  cache_ubuntu22:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-22
      args:
        GO_VERSION: 1.18.2
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: jammy
    command: make deb
  cache_debian10:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-10
      args:
        GO_VERSION: 1.18.2
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: buster
    command: make deb
  cache_debian11:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-11
      args:
        GO_VERSION: 1.18.2
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: bullseye
    command: make deb
