FROM ubuntu:focal
MAINTAINER pyama86 <www.kazu.com@gmail.com>
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qqy update && \
    apt-get install -qqy make debhelper dh-make git devscripts
ENV USER root
COPY . /go/src/github.com/STNS/cache-stnsd
WORKDIR /go/src/github.com/STNS/cache-stnsd
