FROM debian:buster
MAINTAINER pyama86 <www.kazu.com@gmail.com>
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && \
    apt-get install -qq make debhelper dh-make git devscripts
ENV USER root
COPY . /go/src/github.com/STNS/cache-stnsd
WORKDIR /go/src/github.com/STNS/cache-stnsd
RUN git config --global --add safe.directory `pwd`
